What happens if Accounts is over its error budget
alphagov/govuk-developer-docs pull request #3130
Opened 2021-06-14 16:29 UTC by huwd

[Trello](https://trello.com/c/Crj6Z5SW/841-add-slack-alerts-for-when-we-drop-to-50-and-25-remaining-error-budget)

Add notes saying this is no big deal and Icinga alerts are really just
there for the GOV.UK Accounts team to follow up on.

2021-06-17 16:21 UTC, barrucadu approved these changes

2021-06-18 10:49 UTC, jonathanglassman commented on source/manual/slo-error-budget-accounts.html.md
> +When our error budget falls below 25% it will trigger an Icinga alert critical the GOV.UK Accounts team that something is wrong.
"... trigger an Icinga alert critical the GOV.UK Accounts..." - is there a missing word here @huwd?

2021-06-18 10:54 UTC, jonathanglassman commented on source/manual/slo-error-budget-accounts.html.md
> +When our error budget falls below 50% it will trigger an Icinga warning alert warning the GOV.UK Accounts team that something is wrong.
do we need to repeat "warning" here or can we say "...trigger an Icinga alert warning..."

2021-06-18 13:04 UTC, jonathanglassman requested changes
Looks good in general, a couple of comments

2021-06-18 15:30 UTC, closed without merging