GA4 implementation record updates
alphagov/govuk-developer-docs pull request #4045
Opened 2023-06-09 13:45 UTC by andysellick

## What
Update some of the information in the GA4 implementation record section, specifically:

- smart answers
- get emails and RSS link clicks

Also adjust how examples are contained in data and displayed, and adds a 'further reading' page in the docs listing our blog posts to date.

## Why
Part of the work to document our GA4 approach.

Trello card: https://trello.com/c/JbLX3n2C/388-implementation-record-additions-and-improvements

2023-06-14 10:13 UTC, andysellick commented
@AshGDS @JamesCGDS sorry, hold off on reviewing this for a moment - just remembered a small feature I'd like to add.

2023-06-14 11:05 UTC, andysellick commented
Okay, all good to review now, thanks 👍

2023-06-14 16:19 UTC, AshGDS requested changes
Had a glance and looks OK, had a small comment though. Thanks for adding more docs!

2023-06-14 16:19 UTC, AshGDS commented on data/analytics/navigation.yml
> +  desc: blah
Is this meant to be here?

2023-06-15 08:12 UTC, andysellick commented on data/analytics/navigation.yml
> +  desc: blah
Whoops! Sorry, no it isn't. Removed.

2023-06-15 08:43 UTC, AshGDS approved these changes
LGTM :+1:

2023-06-15 09:04 UTC, merged