Remove references to Notify team, in favour of Emergency Alerts
alphagov/govuk-developer-docs pull request #4211
Opened 2023-09-13 10:40 UTC by ChrisBAshton

The Emergency Alerts service is now managed by the Emergency Alerts team.

2023-10-10 07:42 UTC, nicholsj requested changes
Looks good, thanks. Some minor suggested changes for clarity

2023-10-10 07:42 UTC, nicholsj commented on source/manual/emergency-alerts.html.md
>  The Cabinet Office and the Department for Digital, Culture, Media & Sport are developing a ‘cell broadcast’ alert system to enable people whose lives are at risk in an emergency to be rapidly contact
```suggestion
The Cabinet Office and the Department for Digital, Culture, Media & Sport have developed a ‘cell broadcast’ alert system to enable people whose lives are at risk in an emergency to be rapidly contacted via their mobile phone. 
```

2023-10-10 07:42 UTC, nicholsj commented on source/manual/emergency-alerts.html.md
> +of these keys is not restricted to `/alerts` - in principle they could be used to purge any page from the cache. We trust Emergency Alerts to take
```suggestion
of these keys is not restricted to `/alerts` - in principle they could be used to purge any page from the cache. We trust the Emergency Alerts team to take
```

2023-10-10 07:42 UTC, nicholsj commented on source/manual/emergency-alerts.html.md
> +Emergency Alerts have three Fastly API keys with [`purge_select` scope](https://developer.fastly.com/reference/api/auth/#scopes), one for
```suggestion
The Emergency Alerts team have three Fastly API keys with [`purge_select` scope](https://developer.fastly.com/reference/api/auth/#scopes), one for
```

2023-11-15 08:02 UTC, ChrisBAshton commented
Superseded by #4301.

2023-11-15 08:02 UTC, closed without merging