Improvements to documentation around getting Developer Docs running locally
alphagov/govuk-developer-docs pull request #4875
Opened 2024-11-07 17:44 UTC by ChrisBAshton

2025-02-03 14:38 UTC, minhngocd approved these changes
I tried out the instructions:
- local run without docker works without the Github token being in place by using SKIP_PROXY_PAGES as suggested
- docker run still failed with rate limiting when i set the env var in docker-compose.yml to SKIP_PROXY_PAGES true. Does the docker version only work if the Github token is set?

2025-02-03 15:02 UTC, minhngocd requested changes
I tried it out a little bit more. 
Unfortunately never got docker to work... 
Small typo and docker-compose file suggestion, otherwise the rest might be a problem with my machine.

2025-02-03 15:02 UTC, minhngocd commented on README.md
> +      GITHUB_TOKEN: "<fill it in>"
This block is under `govuk-developer-docs-lite`, but when we run `govuk-docker-up` it attaches to the `govuk-developer-docs-app` service, which is the block below. Should we put it in that block instead? or maybe in the common `govuk-developer-docs` above?

2025-02-03 15:02 UTC, minhngocd commented on README.md
> +1. Visit <http://govuk-developer-docs.dev.gov.uk/>
Nevermind, after getting past the rate limiting, I'm also hitting the same error as if i just passed through SKIP PROXY PAGES which is :

```
govuk-developer-docs-app-1  | bundler: failed to load command: middleman (/root/.rbenv/versions/3.3.1/bin/middleman)
govuk-developer-docs-app-1  | /root/.rbenv/versions/3.3.1/lib/ruby/3.3.0/prettyprint.rb:184:in `text': can't convert Middleman::CoreExtensions::Collections::LazyCollectorStep to String (Middleman::CoreExtensions::Collections::LazyCollectorStep#to_str gives Middleman::CoreExtensions::Collections::LazyCollectorStep) (TypeError)
govuk-developer-docs-app-1  | 
govuk-developer-docs-app-1  |       @output << obj
govuk-developer-docs-app-1  |                  ^^^
govuk-developer-docs-app-1  |   from /root/.rbenv/versions/3.3.1/lib/ruby/3.3.0/pp.rb:328:in `pretty_print'
govuk-developer-docs-app-1  |   from /root/.rbenv/versions/3.3.1/lib/ruby/3.3.0/pp.rb:201:in `block in pp'
```

2025-02-03 15:09 UTC, ChrisBAshton commented on README.md
> +- `GOVUK_TOKEN=<your private token>` - token to use to make authenticated requests to GitHub's API. Authenticated requests have a much higher rate limit. *You _will_ need to specify a `GITHUB_TOKEN`
Oops! 🤦

2025-02-05 08:20 UTC, ChrisBAshton commented on README.md
> +      GITHUB_TOKEN: "<fill it in>"
I've now tweaked the doc to make it clearer to add it to both services. 👍 
I don't think it's possible to add to the common `govuk-developer-docs` because the `environment` property in `-lite` and `-app` _override_ that value rather than merge with it.

2025-02-05 16:30 UTC, minhngocd approved these changes
🙏

2025-02-05 16:36 UTC, merged